CREATE INDEX "idx_users_role_id" ON "users" USING btree ("role_id");--> statement-breakpoint
CREATE INDEX "idx_users_status" ON "users" USING btree ("status");--> statement-breakpoint
CREATE INDEX "idx_users_email" ON "users" USING btree ("email");--> statement-breakpoint
CREATE INDEX "idx_medications_name" ON "medications" USING btree ("name");--> statement-breakpoint
CREATE INDEX "idx_medications_brand" ON "medications" USING btree ("brand");--> statement-breakpoint
CREATE INDEX "idx_medications_status" ON "medications" USING btree ("status");--> statement-breakpoint
CREATE INDEX "idx_medication_variants_medication_id" ON "medication_variants" USING btree ("medication_id");--> statement-breakpoint
CREATE INDEX "idx_medication_variants_sku" ON "medication_variants" USING btree ("sku");--> statement-breakpoint
CREATE INDEX "idx_medication_variants_barcode" ON "medication_variants" USING btree ("barcode");--> statement-breakpoint
CREATE INDEX "idx_medication_variants_is_active" ON "medication_variants" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "idx_suppliers_name" ON "suppliers" USING btree ("name");--> statement-breakpoint
CREATE INDEX "idx_suppliers_status" ON "suppliers" USING btree ("status");--> statement-breakpoint
CREATE INDEX "idx_suppliers_contact_email" ON "suppliers" USING btree ("contact_email");--> statement-breakpoint
CREATE INDEX "idx_purchase_orders_user_id" ON "purchase_orders" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_purchase_orders_supplier_id" ON "purchase_orders" USING btree ("supplier_id");--> statement-breakpoint
CREATE INDEX "idx_purchase_orders_order_date" ON "purchase_orders" USING btree ("order_date");--> statement-breakpoint
CREATE INDEX "idx_purchase_orders_status" ON "purchase_orders" USING btree ("status");--> statement-breakpoint
CREATE INDEX "idx_purchase_orders_expected_delivery_date" ON "purchase_orders" USING btree ("expected_delivery_date");--> statement-breakpoint
CREATE INDEX "idx_purchase_order_items_purchase_order_id" ON "purchase_order_items" USING btree ("purchase_order_id");--> statement-breakpoint
CREATE INDEX "idx_purchase_order_items_medication_variant_id" ON "purchase_order_items" USING btree ("medication_variant_id");--> statement-breakpoint
CREATE INDEX "idx_inventory_levels_lot_id" ON "inventory_levels" USING btree ("lot_id");--> statement-breakpoint
CREATE INDEX "idx_inventory_lots_medication_variant_id" ON "inventory_lots" USING btree ("medication_variant_id");--> statement-breakpoint
CREATE INDEX "idx_inventory_lots_expiration_date" ON "inventory_lots" USING btree ("expiration_date");--> statement-breakpoint
CREATE INDEX "idx_inventory_lots_received_date" ON "inventory_lots" USING btree ("received_date");--> statement-breakpoint
CREATE INDEX "idx_inventory_transactions_user_id" ON "inventory_transactions" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_inventory_transactions_lot_id" ON "inventory_transactions" USING btree ("lot_id");--> statement-breakpoint
CREATE INDEX "idx_inventory_transactions_transaction_date" ON "inventory_transactions" USING btree ("transaction_date");--> statement-breakpoint
CREATE INDEX "idx_inventory_transactions_transaction_type" ON "inventory_transactions" USING btree ("transaction_type");--> statement-breakpoint
CREATE INDEX "idx_customers_type" ON "customers" USING btree ("type");--> statement-breakpoint
CREATE INDEX "idx_customers_name" ON "customers" USING btree ("name");--> statement-breakpoint
CREATE INDEX "idx_customers_email" ON "customers" USING btree ("email");--> statement-breakpoint
CREATE INDEX "idx_sales_user_id" ON "sales" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_sales_customer_id" ON "sales" USING btree ("customer_id");--> statement-breakpoint
CREATE INDEX "idx_sales_sale_date" ON "sales" USING btree ("sale_date");--> statement-breakpoint
CREATE INDEX "idx_sales_status" ON "sales" USING btree ("status");--> statement-breakpoint
CREATE INDEX "idx_sales_payment_method" ON "sales" USING btree ("payment_method");--> statement-breakpoint
CREATE INDEX "idx_sale_items_sale_id" ON "sale_items" USING btree ("sale_id");--> statement-breakpoint
CREATE INDEX "idx_sale_items_medication_variant_id" ON "sale_items" USING btree ("medication_variant_id");--> statement-breakpoint
CREATE INDEX "idx_sale_items_lot_id" ON "sale_items" USING btree ("lot_id");